%class Fitwid.EbnfParser;

Start = TypeDecl:[TypeDecl] RuleDefs:Rule* $;
TypeDecl = '%class' Name:/[a-zA-Z_][a-zA-Z0-9_.]*/ ';';
Rule = Name:Identifier '=' Expression:Expression ';';
Expression = Choice | Sequence;
Choice = Sequence ('|' Sequence)+;
Sequence = Element+;
Element = Name:[Identifier ':'] Body:(Group | Optional | Identifier | StringLiteral | RegexLiteral | End) Modifiers:[ZeroOrMore | OneOrMore];
End = '$';
Group = '(' Expression:Expression ')';
Optional = '[' Expression:Expression ']';
Identifier = /[a-zA-Z_][a-zA-Z0-9_]*/;
StringLiteral = /"([^"\n]|\\"|\\)*"/ | /'([^'\n]|\\'|\\)*'/;
RegexLiteral = /\/(\\\/|\\\\|[^\/\n])+\/[imsx]*/;
ZeroOrMore = '*';
OneOrMore = '+';
