Start = Rule*;
Rule = Name:Identifier '=' Expression:Expression ';';
Expression = Choice | Sequence;
Choice = Sequence ('|' Sequence)+;
Sequence = Element+;
Element = Name:[Identifier] Body:(Group | Optional | Identifier | StringLiteral | RegexLiteral) Modifiers:[ZeroOrMore | OneOrMore];
Group = '(' Expression ')';
Optional = '[' Expression ']';
Identifier = /[a-zA-Z_][a-zA-Z0-9_]*/;
StringLiteral = /"([^"\n]|\\"|\\)*"/ | /'([^'\n]|\\'|\\)*'/;
RegexLiteral = /\/([^\/\\\n]|\\\/|\\\\)*\/[imsx]/;
ZeroOrMore = '*';
OneOrMore = '+';
